server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

weather:
  api:
    key: e1616b27727633da850cea985961b0f0