server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: mycert
    enabled-protocols: TLSv1.3

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

weather:
  api:
    key: 97226f349461a244580632e2e285cc22